services:
  emqx1:
    image: emqx:5.0.26
    container_name: mqtt-broker-emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@biometric.mqtt.vsensetech.in"
    # healthcheck:
    #   test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
    #   interval: 5s
    #   timeout: 25s
    #   retries: 5
    # networks:
    #   emqx-bridge:
    #     aliases:
    #     - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 

    # volumes:
    #   - ./emqx:/opt/emqx