
services:
  emqx-enterprise:
    image: emqx/emqx-enterprise:5.8.4
    container_name: emqx-enterprise
    restart: always
    ports:
      - "1883:1883"    # MQTT (TCP)
      - "8083:8083"    # WebSocket
      - "8084:8084"    # Secure WebSocket (SSL)
      - "8883:8883"    # MQTT (SSL/TLS)
      - "18083:18083"  # Dashboard
    volumes:
      - ./data:/opt/emqx/data
      - ./log:/opt/emqx/log
